apiVersion: v1
kind: Service
metadata:
  name: demo1
  labels:
    app: demo1
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: demo1